name: Workflow Triggered by Repository Dispatch

on:
  repository_dispatch:
    types:
      - workflow-trigger  # Use the same custom event name as in Repository A
  push:
    branches: ["newversion"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: # Use the same custom event name as in Repository A

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "arpitjindal-pythonD"
          git config --global user.email "arpit.jindal@protonmail.com"

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      
      - name: Build App
        run:  |
          cd azure-arc-jumpstart-app
          npm run deploy
  deploy:
        environment:
          name: github-pages
          url: ${{steps.deployment.outputs.page_url}}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v2
