name: Deploy to GitHub Pages

on:
  push:
    branches:
      - newversion

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2 # This action checks out your repo

    - name: Install and Build # Add this step to install and build your project (if required)
      run: |
        cd azure-arc-jumpstart-app
        npm install
        npm run build

    - name: Deploy 
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # Target branch to deploy to
        folder: ./azure-arc-jumpstart-app/build # Folder (or path) containing your app's build artifacts
        clean: true # Automatically remove old files from the deployment branch
        token: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided by GitHub Actions
