name: Build and deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - newversion
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false 

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: npm install, build, and test
        run: |
          cd azure-arc-jumpstart-app
          npm run fetch-docs  
          npm install
          npm run build

      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # Target branch to deploy to
          folder: ./azure-arc-jumpstart-app/build # Folder (or path) containing your app's build artifacts
          clean: true # Automatically remove old files from the deployment branch
          token: ${{ secrets.GITHUB_TOKEN }} # GitHub token, automatically provided by GitHub Actions
