name: Deploy to GitHub Pages

on:
  push:
    branches:
      - newversion

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd azure-arc-jumpstart-app
          npm install
          npm install --save gh-pages

      - name: Build site
        run: |
          cd azure-arc-jumpstart-app
          npm run build  # Replace with your build command

      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          cd azure-arc-jumpstart-app
          npm run deploy
        env:
          user_name: 'arpitjindal-pythonD'
          user_email: 'arpit.jindal@protonmail.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
